apiVersion: v1
kind: Service
metadata:
  name: clo835-mock
  labels:
    app: node-app
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 30000
  selector:
    app: node-app
    component: frontend